name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: chawyehsu/setup-moonup@v1
      - run: moon fmt --check
      - run: moon check --deny-warn

  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        target: [wasm-gc, wasm, js, native]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: chawyehsu/setup-moonup@v1
      - run: moon test --target ${{ matrix.target }}
