name: Publish

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: chawyehsu/setup-moonup@v1
      - run: moon publish --dry-run
      - name: Publish to mooncakes.io
        run: |
          mkdir -p ~/.moon
          echo "$MOONCAKES_TOKEN" > ~/.moon/credentials.json
          moon publish
        env:
          MOONCAKES_TOKEN: ${{ secrets.MOONCAKES_TOKEN }}

  github-release:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "${{ github.ref_name }}" --generate-notes
